/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nba;

import Entidades.Equipos;
import Entidades.Jugadores;
import java.math.BigDecimal;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;

/**
 *
 * @author Manu
 */
public class NBA {
    public static void main(String[] args) {
        //SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
        //String fechaAtlanta = "01/01/1946";
        //Date fecha = null;
     
    }
    
        //OPERACIONES SOBRE LA BASE DE DATOS
        //Nombre de cada equipo
        Equipos equipoAtlanta = new Equipos(0, "Atlanta Hawks");
        Equipos equipoBoston = new Equipos(0, "Boston Celtics");
        Equipos equipoBrooklyn = new Equipos(0, "Brooklyn Nets");
        Equipos equipoCharlotte = new Equipos(0, "Charlotte Hornets");
        Equipos equipoChicago = new Equipos(0, "Chicago Bulls");
        Equipos equipoCleveland = new Equipos(0, "Cleveland Cavaliers");
        Equipos equipoDallas = new Equipos(0, "Dallas Mavericks");
        Equipos equipoDenver = new Equipos(0, "Denver Nuggets");
        Equipos equipoDetroit = new Equipos(0, "Detroit Pistons");
        Equipos equipoGolden = new Equipos(0, "Golden State Warriors");
        Equipos equipoHouston = new Equipos(0, "Houston Rockets");
        Equipos equipoIndiana = new Equipos(0, "Indiana Pacers");
        Equipos equipoLAC = new Equipos(0, "Los Angeles Clippers");
        Equipos equipoLAL = new Equipos(0, "Los Angeles Lakers");
        Equipos equipoMemphis = new Equipos(0, "Memphis Grizzlies");
        Equipos equipoMiami = new Equipos(0, "Miami Heat");
        Equipos equipoBucks = new Equipos(0, "Milwaukee Bucks");
        Equipos equipoMinnesota = new Equipos(0, "Minnesota Timberwolves");
        Equipos equipoNOP = new Equipos(0, "New Orleans Pelicans");
        Equipos equipoNYK = new Equipos(0, "New York Knicks");
        Equipos equipoOCT = new Equipos(0, "Oklahoma City Thunder");
        Equipos equipoMagic = new Equipos(0, "Orlando Magic");
        Equipos equipoPhila = new Equipos(0, "Philadelphia 76ers");
        Equipos equipoSuns = new Equipos(0, "Phoenix Suns");
        Equipos equipoPTB = new Equipos(0, "Portland Trail Blazers");
        Equipos equipoKings = new Equipos(0, "Sacramento Kings");
        Equipos equipoSpurs = new Equipos(0, "San Antonio Spurs");
        Equipos equipoRaptors = new Equipos(0, "Toronto Raptors");
        Equipos equipoUtah = new Equipos(0, "Utah Jazz");
        Equipos equipoWizards = new Equipos(0, "Washington Wizards");
        
        // Nombre de cada jugador
        Jugadores jugador1 = new Jugadores(0, "Trae", "Young");
        Jugadores jugador2 = new Jugadores(0, "Kent", "Bazemore");
        Jugadores jugador3 = new Jugadores(0, "Vince", "Carter");
        Jugadores jugador4 = new Jugadores(0, "John", "Collins");
        Jugadores jugador5 = new Jugadores(0, "Miles", "Plumlee");
        Jugadores jugador6 = new Jugadores(0, "Isaac", "Humphries");
        Jugadores jugador7 = new Jugadores(0, "Kyrie", "Irving");
        Jugadores jugador8 = new Jugadores(0, "Marcus", "Smart");
        Jugadores jugador9 = new Jugadores(0, "Jaylen", "Brown");
        Jugadores jugador10 = new Jugadores(0, "Jayson", "Tatum");
        Jugadores jugador11 = new Jugadores(0, "Gordon", "Hayward");
        Jugadores jugador12 = new Jugadores(0, "Al", "Horford");
        Jugadores jugador13 = new Jugadores(0, "D´Angelo", "Russell");
        Jugadores jugador14 = new Jugadores(0, "Joe", "Harris");
        Jugadores jugador15 = new Jugadores(0, "Caris", "LeVert");
        Jugadores jugador16 = new Jugadores(0, "DeMarre", "Carroll");
        Jugadores jugador17 = new Jugadores(0, "Jarrett", "Allen");
        Jugadores jugador18 = new Jugadores(0, "Kemba", "Walker");
        Jugadores jugador19 = new Jugadores(0, "Nicolas", "Batum");
        Jugadores jugador20 = new Jugadores(0, "M.", "Kidd-Gilchrist");
        Jugadores jugador21 = new Jugadores(0, "Marvin", "Williams");
        Jugadores jugador22 = new Jugadores(0, "Cody", "Zeller");
        Jugadores jugador23 = new Jugadores(0, "Willy", "Hernangómez");
        Jugadores jugador24 = new Jugadores(0, "Kris", "Dunn");
        Jugadores jugador25 = new Jugadores(0, "Zach", "LaVine");
        Jugadores jugador26 = new Jugadores(0, "Otto", "Porter");
        Jugadores jugador27 = new Jugadores(0, "Lauri", "Markkanen");
        Jugadores jugador28 = new Jugadores(0, "Robin", "Lopez");
        Jugadores jugador29 = new Jugadores(0, "M.", "Dellavedova");
        Jugadores jugador30 = new Jugadores(0, "Brandon", "Knight");
        Jugadores jugador31 = new Jugadores(0, "Kevin", "Love");
        Jugadores jugador32 = new Jugadores(0, "Ante", "Zizic");
        Jugadores jugador33 = new Jugadores(0, "J.R.", "Smith");
        Jugadores jugador34 = new Jugadores(0, "Luka", "Doncic");
        Jugadores jugador35 = new Jugadores(0, "Tim", "Hardaway Jr");
        Jugadores jugador36 = new Jugadores(0, "D.", "Finney-Smith");
        Jugadores jugador37 = new Jugadores(0, "Kristaps", "Porzingis");
        Jugadores jugador38 = new Jugadores(0, "Salah", "Mejri");
        Jugadores jugador39 = new Jugadores(0, "Jamal", "Murray");
        Jugadores jugador40 = new Jugadores(0, "Will", "Barton");
        Jugadores jugador41 = new Jugadores(0, "Juancho", "Hernangómez");
        Jugadores jugador42 = new Jugadores(0, "Paul", "Millsap");
        Jugadores jugador43 = new Jugadores(0, "Nikola", "Jokic");
        Jugadores jugador44 = new Jugadores(0, "Mason", "Plumlee");
        Jugadores jugador45 = new Jugadores(0, "Reggie", "Jackson");
        Jugadores jugador46 = new Jugadores(0, "José Manuel", "Calderón");
        Jugadores jugador47 = new Jugadores(0, "Langston", "Galloway");
        Jugadores jugador48 = new Jugadores(0, "Wayne", "Ellington");
        Jugadores jugador49 = new Jugadores(0, "Blake", "Griffin");
        Jugadores jugador50 = new Jugadores(0, "Andre", "Drummond");
        Jugadores jugador51 = new Jugadores(0, "Stephen", "Curry");
        Jugadores jugador52 = new Jugadores(0, "Klay", "Thompson");
        Jugadores jugador53 = new Jugadores(0, "Andre", "Iguodala");
        Jugadores jugador54 = new Jugadores(0, "Kevin", "Durant");
        Jugadores jugador55 = new Jugadores(0, "Draymond", "Green");
        Jugadores jugador56 = new Jugadores(0, "DeMarcus", "Cousins");
        Jugadores jugador57 = new Jugadores(0, "Chris", "Paul");
        Jugadores jugador58 = new Jugadores(0, "Eric", "Gordon");
        Jugadores jugador59 = new Jugadores(0, "James", "Harden");
        Jugadores jugador60 = new Jugadores(0, "P.J.", "Tucker");
        Jugadores jugador61 = new Jugadores(0, "Clint", "Capela");
        Jugadores jugador62 = new Jugadores(0, "Darren", "Collison");
        Jugadores jugador63 = new Jugadores(0, "Tyreke", "Evans");
        Jugadores jugador64 = new Jugadores(0, "Victor", "Oladipo");
        Jugadores jugador65 = new Jugadores(0, "Bojan", "Bogdanovic");
        Jugadores jugador66 = new Jugadores(0, "Thaddeus", "Young");
        Jugadores jugador67 = new Jugadores(0, "Myles", "Turner");
        Jugadores jugador68 = new Jugadores(0, "Patrick", "Beverley");
        Jugadores jugador69 = new Jugadores(0, "Louis", "Williams");
        Jugadores jugador70 = new Jugadores(0, "Garrett", "Temple");
        Jugadores jugador71 = new Jugadores(0, "Danilo", "Gallinari");
        Jugadores jugador72 = new Jugadores(0, "Ivica", "Zubac");
        Jugadores jugador73 = new Jugadores(0, "Rajon", "Rondo");
        Jugadores jugador74 = new Jugadores(0, "Brandon", "Ingram");
        Jugadores jugador75 = new Jugadores(0, "LeBron", "James");
        Jugadores jugador76 = new Jugadores(0, "Kyle", "Kuzma");
        Jugadores jugador77 = new Jugadores(0, "JaVale", "McGee");
        Jugadores jugador78 = new Jugadores(0, "Mike", "Conley");
        Jugadores jugador79 = new Jugadores(0, "C.J.", "Miles");
        Jugadores jugador80 = new Jugadores(0, "Justin", "Holiday");
        Jugadores jugador81 = new Jugadores(0, "Bruno", "Caboclo");
        Jugadores jugador82 = new Jugadores(0, "Jonas", "Valanciunas");
        Jugadores jugador83 = new Jugadores(0, "Joakim", "Noah");
        Jugadores jugador84 = new Jugadores(0, "Goran", "Dragic");
        Jugadores jugador85 = new Jugadores(0, "Dion", "Waiters");
        Jugadores jugador86 = new Jugadores(0, "Derrick", "Jones Jr");
        Jugadores jugador87 = new Jugadores(0, "Kelly", "Olynik");
        Jugadores jugador88 = new Jugadores(0, "Bam", "Adebayo");
        Jugadores jugador89 = new Jugadores(0, "Eric", "Bledsoe");
        Jugadores jugador90 = new Jugadores(0, "George", "Hill");
        Jugadores jugador91 = new Jugadores(0, "Malcolm", "Brogdon");
        Jugadores jugador92 = new Jugadores(0, "Khris", "Middleton");
        Jugadores jugador93 = new Jugadores(0, "Giannis", "Antetokounmpo");
        Jugadores jugador94 = new Jugadores(0, "Nikola", "Mirotic");
        Jugadores jugador95 = new Jugadores(0, "Brook", "Lopez");
        Jugadores jugador96 = new Jugadores(0, "Pau", "Gasol");
        Jugadores jugador97 = new Jugadores(0, "Jeff", "Teague");
        Jugadores jugador98 = new Jugadores(0, "Derrick", "Rose");
        Jugadores jugador99 = new Jugadores(0, "Luol", "Deng");
        Jugadores juga0 = new Jugadores(0, "Dario", "Savic");
        Jugadores juga1 = new Jugadores(0, "Karl-Anthony", "Towns");
        Jugadores juga2 = new Jugadores(0, "Elfrid", "Payton");
        Jugadores juga3 = new Jugadores(0, "Jrue", "Holiday");
        Jugadores juga4 = new Jugadores(0, "Kenrich", "Williams");
        Jugadores juga5 = new Jugadores(0, "Julius", "Randle");
        Jugadores juga6 = new Jugadores(0, "Anthony", "Davis");
        Jugadores juga7 = new Jugadores(0, "Dennis", "Smith Jr");
        Jugadores juga8 = new Jugadores(0, "John", "Jenkins");
        Jugadores juga9 = new Jugadores(0, "Mario", "Hezonja");
        Jugadores juga10 = new Jugadores(0, "Lance", "Thomas");
        Jugadores juga11 = new Jugadores(0, "DeAndre", "Jordan");
        Jugadores juga12 = new Jugadores(0, "Russell", "Westbrook");
        Jugadores juga13 = new Jugadores(0, "Dennis", "Schröder");
        Jugadores juga14 = new Jugadores(0, "Hamidou", "Diallo");
        Jugadores juga15 = new Jugadores(0, "Paul", "George");
        Jugadores juga16 = new Jugadores(0, "Jeremi", "Grant");
        Jugadores juga17 = new Jugadores(0, "Steven", "Adams");
        Jugadores juga18 = new Jugadores(0, "D.J.", "Augustin");
        Jugadores juga19 = new Jugadores(0, "M.", "Carter-Williams");
        Jugadores juga20 = new Jugadores(0, "Terrence", "Ross");
        Jugadores juga21 = new Jugadores(0, "Jonathan", "Isaac");
        Jugadores juga22 = new Jugadores(0, "Aaron", "Gordon");
        Jugadores juga23 = new Jugadores(0, "Nikola", "Vucevic");
        Jugadores juga24 = new Jugadores(0, "Ben", "Simmons");
        Jugadores juga25 = new Jugadores(0, "J.J.", "Redick");
        Jugadores juga26 = new Jugadores(0, "Jimmy", "Butler");
        Jugadores juga27 = new Jugadores(0, "Tobias", "Harris");
        Jugadores juga28 = new Jugadores(0, "Joel", "Embiid");
        Jugadores juga29 = new Jugadores(0, "Boban", "Marjanovic");
        Jugadores juga30 = new Jugadores(0, "Tyler", "Johnson");
        Jugadores juga31 = new Jugadores(0, "Devin", "Booker");
        Jugadores juga32 = new Jugadores(0, "Kelly", "Oubre");
        Jugadores juga33 = new Jugadores(0, "Josh", "Jackson");
        Jugadores juga34 = new Jugadores(0, "Dragan", "Bender");
        Jugadores juga35 = new Jugadores(0, "Damian", "Lillard");
        Jugadores juga36 = new Jugadores(0, "Seth", "Curry");
        Jugadores juga37 = new Jugadores(0, "C.J.", "McCollum");
        Jugadores juga38 = new Jugadores(0, "Evan", "Turner");
        Jugadores juga39 = new Jugadores(0, "Al-Farouq", "Aminu");
        Jugadores juga40 = new Jugadores(0, "Jusuf", "Nurkic");
        Jugadores juga41 = new Jugadores(0, "Yogi", "Ferrell");
        Jugadores juga42 = new Jugadores(0, "Alec", "Burks");
        Jugadores juga43 = new Jugadores(0, "Bogdan", "Bogdanovic");
        Jugadores juga44 = new Jugadores(0, "Harrison", "Barnes");
        Jugadores juga45 = new Jugadores(0, "W.", "Cauley-Stein");
        Jugadores juga46 = new Jugadores(0, "Derrick", "White");
        Jugadores juga47 = new Jugadores(0, "Marco", "Bellinelli");
        Jugadores juga48 = new Jugadores(0, "DeMar", "DeRozan");
        Jugadores juga49 = new Jugadores(0, "Rudy", "Gay");
        Jugadores juga50 = new Jugadores(0, "LaMarcus", "Aldridge");
        Jugadores juga51 = new Jugadores(0, "Kyle", "Lowry");
        Jugadores juga52 = new Jugadores(0, "Danny", "Green");
        Jugadores juga53 = new Jugadores(0, "Kawhi", "Leonard");
        Jugadores juga54 = new Jugadores(0, "Pascal", "Siakam");
        Jugadores juga55 = new Jugadores(0, "Marc", "Gasol");
        Jugadores juga56 = new Jugadores(0, "Serge", "Ibaka");
        Jugadores juga57 = new Jugadores(0, "Ricky", "Rubio");
        Jugadores juga58 = new Jugadores(0, "Donovan", "Mitchell");
        Jugadores juga59 = new Jugadores(0, "Kyle", "Korver");
        Jugadores juga60 = new Jugadores(0, "Thabo", "Sefolosha");
        Jugadores juga61 = new Jugadores(0, "Derrick", "Favors");
        Jugadores juga62 = new Jugadores(0, "Rudy", "Gobert");
        Jugadores juga63 = new Jugadores(0, "Tomas", "Satoransky");
        Jugadores juga64 = new Jugadores(0, "John", "Wall");
        Jugadores juga65 = new Jugadores(0, "Bradley", "Beal");
        Jugadores juga66 = new Jugadores(0, "Trevor", "Ariza");
        Jugadores juga67 = new Jugadores(0, "Javari", "Parker");
        Jugadores juga68 = new Jugadores(0, "Dwight", "Howard");
        
        //Número de Camiseta de cada jugador
    public void numeroJugadores() {
        jugador1.setNºcamiseta("11");
        jugador2.setNºcamiseta("24");
        jugador3.setNºcamiseta("15");
        jugador4.setNºcamiseta("20");
        jugador5.setNºcamiseta("18");
        jugador6.setNºcamiseta("8");
        jugador7.setNºcamiseta("11");
        jugador8.setNºcamiseta("36");
        jugador9.setNºcamiseta("7");
        jugador10.setNºcamiseta("0");
        jugador11.setNºcamiseta("20");
        jugador12.setNºcamiseta("42");
        jugador13.setNºcamiseta("1");
        jugador14.setNºcamiseta("12");
        jugador15.setNºcamiseta("22");
        jugador16.setNºcamiseta("9");
        jugador17.setNºcamiseta("31");
        jugador18.setNºcamiseta("15");
        jugador19.setNºcamiseta("5");
        jugador20.setNºcamiseta("14");
        jugador21.setNºcamiseta("2");
        jugador22.setNºcamiseta("40");
        jugador23.setNºcamiseta("41");
        jugador24.setNºcamiseta("32");
        jugador25.setNºcamiseta("8");
        jugador26.setNºcamiseta("22");
        jugador27.setNºcamiseta("24");
        jugador28.setNºcamiseta("42");
        jugador29.setNºcamiseta("18");
        jugador30.setNºcamiseta("20");
        jugador31.setNºcamiseta("0");
        jugador32.setNºcamiseta("41");
        jugador33.setNºcamiseta("5");
        jugador34.setNºcamiseta("77");
        jugador35.setNºcamiseta("11"); 
        jugador36.setNºcamiseta("10");
        jugador37.setNºcamiseta("6");
        jugador38.setNºcamiseta("50");
        jugador39.setNºcamiseta("27");
        jugador40.setNºcamiseta("5");
        jugador41.setNºcamiseta("41");
        jugador42.setNºcamiseta("4");
        jugador43.setNºcamiseta("15");
        jugador44.setNºcamiseta("24");
        jugador45.setNºcamiseta("1");
        jugador46.setNºcamiseta("81");
        jugador47.setNºcamiseta("9");
        jugador48.setNºcamiseta("20");
        jugador49.setNºcamiseta("23");
        jugador50.setNºcamiseta("0");
        jugador51.setNºcamiseta("30");
        jugador52.setNºcamiseta("11");
        jugador53.setNºcamiseta("9");
        jugador54.setNºcamiseta("35");
        jugador55.setNºcamiseta("23");
        jugador56.setNºcamiseta("0");
        jugador57.setNºcamiseta("3");
        jugador58.setNºcamiseta("10");
        jugador59.setNºcamiseta("13");
        jugador60.setNºcamiseta("17");
        jugador61.setNºcamiseta("15");
        jugador62.setNºcamiseta("2");
        jugador63.setNºcamiseta("12");
        jugador64.setNºcamiseta("4");
        jugador65.setNºcamiseta("44");
        jugador66.setNºcamiseta("21");
        jugador67.setNºcamiseta("33");
        jugador68.setNºcamiseta("21");
        jugador69.setNºcamiseta("23");
        jugador70.setNºcamiseta("17");
        jugador71.setNºcamiseta("8");
        jugador72.setNºcamiseta("40");
        jugador73.setNºcamiseta("9");
        jugador74.setNºcamiseta("14");
        jugador75.setNºcamiseta("23");
        jugador76.setNºcamiseta("0");
        jugador77.setNºcamiseta("7");
        jugador78.setNºcamiseta("11");
        jugador79.setNºcamiseta("6");
        jugador80.setNºcamiseta("7");
        jugador81.setNºcamiseta("5");
        jugador82.setNºcamiseta("17");
        jugador83.setNºcamiseta("55");
        jugador84.setNºcamiseta("7");
        jugador85.setNºcamiseta("11");
        jugador86.setNºcamiseta("5");
        jugador87.setNºcamiseta("9");
        jugador88.setNºcamiseta("13");
        jugador89.setNºcamiseta("6");
        jugador90.setNºcamiseta("3");
        jugador91.setNºcamiseta("13");
        jugador92.setNºcamiseta("22");
        jugador93.setNºcamiseta("34");
        jugador94.setNºcamiseta("41");
        jugador95.setNºcamiseta("11");
        jugador96.setNºcamiseta("17");
        jugador97.setNºcamiseta("0");
        jugador98.setNºcamiseta("25");
        jugador99.setNºcamiseta("9");
        juga0.setNºcamiseta("36");
        juga1.setNºcamiseta("32");
        juga2.setNºcamiseta("4");
        juga3.setNºcamiseta("11");
        juga4.setNºcamiseta("34");
        juga5.setNºcamiseta("30");
        juga6.setNºcamiseta("23");
        juga7.setNºcamiseta("5");
        juga8.setNºcamiseta("30");
        juga9.setNºcamiseta("8");
        juga10.setNºcamiseta("42");
        juga11.setNºcamiseta("6");
        juga12.setNºcamiseta("0");
        juga13.setNºcamiseta("17");
        juga14.setNºcamiseta("6");
        juga15.setNºcamiseta("13");
        juga16.setNºcamiseta("9");
        juga17.setNºcamiseta("12");
        juga18.setNºcamiseta("14");
        juga19.setNºcamiseta("7");
        juga20.setNºcamiseta("31");
        juga21.setNºcamiseta("1");
        juga22.setNºcamiseta("00");
        juga23.setNºcamiseta("9");
        juga24.setNºcamiseta("25");
        juga25.setNºcamiseta("17");
        juga26.setNºcamiseta("23");
        juga27.setNºcamiseta("33");
        juga28.setNºcamiseta("21");
        juga29.setNºcamiseta("51");
        juga30.setNºcamiseta("16");
        juga31.setNºcamiseta("1");
        juga32.setNºcamiseta("3");
        juga33.setNºcamiseta("20");
        juga34.setNºcamiseta("35");
        juga35.setNºcamiseta("0");
        juga36.setNºcamiseta("31");
        juga37.setNºcamiseta("3");
        juga38.setNºcamiseta("1");
        juga39.setNºcamiseta("8");
        juga40.setNºcamiseta("27");
        juga41.setNºcamiseta("3");
        juga42.setNºcamiseta("13");
        juga43.setNºcamiseta("8");
        juga44.setNºcamiseta("40");
        juga45.setNºcamiseta("00");
        juga46.setNºcamiseta("4");
        juga47.setNºcamiseta("18");
        juga48.setNºcamiseta("10");
        juga49.setNºcamiseta("22");
        juga50.setNºcamiseta("12");
        juga51.setNºcamiseta("7");
        juga52.setNºcamiseta("14");
        juga53.setNºcamiseta("2");
        juga54.setNºcamiseta("43");
        juga55.setNºcamiseta("33");
        juga56.setNºcamiseta("9");
        juga57.setNºcamiseta("3");
        juga58.setNºcamiseta("45");
        juga59.setNºcamiseta("26");
        juga60.setNºcamiseta("22");
        juga61.setNºcamiseta("15");
        juga62.setNºcamiseta("27");
        juga63.setNºcamiseta("31");
        juga64.setNºcamiseta("2");
        juga65.setNºcamiseta("3");
        juga66.setNºcamiseta("1");
        juga67.setNºcamiseta("12");
        juga68.setNºcamiseta("21");
    }    
        // Asignar el equipo a cada jugador
    public void EquipoJugador() {
        jugador1.setEquipo(equipoAtlanta);
        jugador2.setEquipo(equipoAtlanta);
        jugador3.setEquipo(equipoAtlanta);
        jugador4.setEquipo(equipoAtlanta);
        jugador5.setEquipo(equipoAtlanta);
        jugador6.setEquipo(equipoAtlanta);
        jugador7.setEquipo(equipoBoston);
        jugador8.setEquipo(equipoBoston);
        jugador9.setEquipo(equipoBoston);
        jugador10.setEquipo(equipoBoston);
        jugador11.setEquipo(equipoBoston);
        jugador12.setEquipo(equipoBoston);
        jugador13.setEquipo(equipoBrooklyn);
        jugador14.setEquipo(equipoBrooklyn);
        jugador15.setEquipo(equipoBrooklyn);
        jugador16.setEquipo(equipoBrooklyn);
        jugador17.setEquipo(equipoBrooklyn);
        jugador18.setEquipo(equipoCharlotte);
        jugador19.setEquipo(equipoCharlotte);
        jugador20.setEquipo(equipoCharlotte);
        jugador21.setEquipo(equipoCharlotte);
        jugador22.setEquipo(equipoCharlotte);
        jugador23.setEquipo(equipoCharlotte);
        jugador24.setEquipo(equipoChicago);
        jugador25.setEquipo(equipoChicago);
        jugador26.setEquipo(equipoChicago);
        jugador27.setEquipo(equipoChicago);
        jugador28.setEquipo(equipoChicago);
        jugador29.setEquipo(equipoCleveland);
        jugador30.setEquipo(equipoCleveland);
        jugador31.setEquipo(equipoCleveland);
        jugador32.setEquipo(equipoCleveland);
        jugador33.setEquipo(equipoCleveland);
        jugador34.setEquipo(equipoDallas);
        jugador35.setEquipo(equipoDallas);
        jugador36.setEquipo(equipoDallas);
        jugador37.setEquipo(equipoDallas);
        jugador38.setEquipo(equipoDallas);
        jugador39.setEquipo(equipoDenver);
        jugador40.setEquipo(equipoDenver);
        jugador41.setEquipo(equipoDenver);
        jugador42.setEquipo(equipoDenver);
        jugador43.setEquipo(equipoDenver);
        jugador44.setEquipo(equipoDenver);
        jugador45.setEquipo(equipoDetroit);
        jugador46.setEquipo(equipoDetroit);
        jugador47.setEquipo(equipoDetroit);
        jugador48.setEquipo(equipoDetroit);
        jugador49.setEquipo(equipoDetroit);
        jugador50.setEquipo(equipoDetroit);
        jugador51.setEquipo(equipoGolden);
        jugador52.setEquipo(equipoGolden);
        jugador53.setEquipo(equipoGolden);
        jugador54.setEquipo(equipoGolden);
        jugador55.setEquipo(equipoGolden);
        jugador56.setEquipo(equipoGolden);
        jugador57.setEquipo(equipoHouston);
        jugador58.setEquipo(equipoHouston);
        jugador59.setEquipo(equipoHouston);
        jugador60.setEquipo(equipoHouston);
        jugador61.setEquipo(equipoHouston);
        jugador62.setEquipo(equipoIndiana);
        jugador63.setEquipo(equipoIndiana);
        jugador64.setEquipo(equipoIndiana);
        jugador65.setEquipo(equipoIndiana);
        jugador66.setEquipo(equipoIndiana);
        jugador67.setEquipo(equipoIndiana);
        jugador68.setEquipo(equipoLAC);
        jugador69.setEquipo(equipoLAC);
        jugador70.setEquipo(equipoLAC);
        jugador71.setEquipo(equipoLAC);
        jugador72.setEquipo(equipoLAC);
        jugador73.setEquipo(equipoLAL);
        jugador74.setEquipo(equipoLAL);
        jugador75.setEquipo(equipoLAL);
        jugador76.setEquipo(equipoLAL);
        jugador77.setEquipo(equipoLAL);
        jugador78.setEquipo(equipoMemphis);
        jugador79.setEquipo(equipoMemphis);
        jugador80.setEquipo(equipoMemphis);
        jugador81.setEquipo(equipoMemphis);
        jugador82.setEquipo(equipoMemphis);
        jugador83.setEquipo(equipoMemphis);
        jugador84.setEquipo(equipoMiami);
        jugador85.setEquipo(equipoMiami);
        jugador86.setEquipo(equipoMiami);
        jugador87.setEquipo(equipoMiami);
        jugador88.setEquipo(equipoMiami);
        jugador89.setEquipo(equipoBucks);
        jugador90.setEquipo(equipoBucks);
        jugador91.setEquipo(equipoBucks);
        jugador92.setEquipo(equipoBucks);
        jugador93.setEquipo(equipoBucks);
        jugador94.setEquipo(equipoBucks);
        jugador95.setEquipo(equipoBucks);
        jugador96.setEquipo(equipoBucks);
        jugador97.setEquipo(equipoMinnesota);
        jugador98.setEquipo(equipoMinnesota);
        jugador99.setEquipo(equipoMinnesota);
        juga0.setEquipo(equipoMinnesota);
        juga1.setEquipo(equipoMinnesota);
        juga2.setEquipo(equipoNOP);
        juga3.setEquipo(equipoNOP);
        juga4.setEquipo(equipoNOP);
        juga5.setEquipo(equipoNOP);
        juga6.setEquipo(equipoNOP);
        juga7.setEquipo(equipoNYK);
        juga8.setEquipo(equipoNYK);
        juga9.setEquipo(equipoNYK);
        juga10.setEquipo(equipoNYK);
        juga11.setEquipo(equipoNYK);
        juga12.setEquipo(equipoOCT);
        juga13.setEquipo(equipoOCT);
        juga14.setEquipo(equipoOCT);
        juga15.setEquipo(equipoOCT);
        juga16.setEquipo(equipoOCT);
        juga17.setEquipo(equipoOCT);
        juga18.setEquipo(equipoMagic);
        juga19.setEquipo(equipoMagic);
        juga20.setEquipo(equipoMagic);
        juga21.setEquipo(equipoMagic);
        juga22.setEquipo(equipoMagic);
        juga23.setEquipo(equipoMagic);
        juga24.setEquipo(equipoPhila);
        juga25.setEquipo(equipoPhila);
        juga26.setEquipo(equipoPhila);
        juga27.setEquipo(equipoPhila);
        juga28.setEquipo(equipoPhila);
        juga29.setEquipo(equipoPhila);
        juga30.setEquipo(equipoSuns);
        juga31.setEquipo(equipoSuns);
        juga32.setEquipo(equipoSuns);
        juga33.setEquipo(equipoSuns);
        juga34.setEquipo(equipoSuns);
        juga35.setEquipo(equipoPTB);
        juga36.setEquipo(equipoPTB);
        juga37.setEquipo(equipoPTB);
        juga38.setEquipo(equipoPTB);
        juga39.setEquipo(equipoPTB);
        juga40.setEquipo(equipoPTB);
        juga41.setEquipo(equipoKings);
        juga42.setEquipo(equipoKings);
        juga43.setEquipo(equipoKings);
        juga44.setEquipo(equipoKings);
        juga45.setEquipo(equipoKings);
        juga46.setEquipo(equipoSpurs);
        juga47.setEquipo(equipoSpurs);
        juga48.setEquipo(equipoSpurs);
        juga49.setEquipo(equipoSpurs);
        juga50.setEquipo(equipoSpurs);
        juga51.setEquipo(equipoRaptors);
        juga52.setEquipo(equipoRaptors);
        juga53.setEquipo(equipoRaptors);
        juga54.setEquipo(equipoRaptors);
        juga55.setEquipo(equipoRaptors);
        juga56.setEquipo(equipoRaptors);
        juga57.setEquipo(equipoUtah);
        juga58.setEquipo(equipoUtah);
        juga59.setEquipo(equipoUtah);
        juga60.setEquipo(equipoUtah);
        juga61.setEquipo(equipoUtah);
        juga62.setEquipo(equipoUtah);
        juga63.setEquipo(equipoWizards);
        juga64.setEquipo(equipoWizards);
        juga65.setEquipo(equipoWizards);
        juga66.setEquipo(equipoWizards);
        juga67.setEquipo(equipoWizards);
        juga68.setEquipo(equipoWizards);
        }    
        //Asignar Posición de cada jugador
    public void PosicionJugador() {
        jugador1.setPosición("Base");
        jugador2.setPosición("Escolta");
        jugador3.setPosición("Alero");
        jugador4.setPosición("Ala-Pivot");
        jugador5.setPosición("Pivot");
        jugador6.setPosición("Pivot");
        jugador7.setPosición("Base");
        jugador8.setPosición("Escolta");
        jugador9.setPosición("Escolta");
        jugador10.setPosición("Alero");
        jugador11.setPosición("Alero");
        jugador12.setPosición("Pivot");
        jugador13.setPosición("Base");
        jugador14.setPosición("Escolta");
        jugador15.setPosición("Alero");
        jugador16.setPosición("Ala-Pivot");
        jugador17.setPosición("Pivot");
        jugador18.setPosición("Base");
        jugador19.setPosición("Escolta");
        jugador20.setPosición("Alero");
        jugador21.setPosición("Ala-Pivot");
        jugador22.setPosición("Pivot");
        jugador23.setPosición("Pivot");
        jugador24.setPosición("Base");
        jugador25.setPosición("Escolta");
        jugador26.setPosición("Alero");
        jugador27.setPosición("Ala-Pivot");
        jugador28.setPosición("Pivot");
        jugador29.setPosición("Base");
        jugador30.setPosición("Escolta");
        jugador31.setPosición("Ala-Pivot");
        jugador32.setPosición("Pivot");
        jugador33.setPosición("Escolta");
        jugador34.setPosición("Base");
        jugador35.setPosición("Escolta");
        jugador36.setPosición("Alero");
        jugador37.setPosición("Ala-Pivot");
        jugador38.setPosición("Pivot");
        jugador39.setPosición("Base");
        jugador40.setPosición("Alero");
        jugador41.setPosición("Alero");
        jugador42.setPosición("Ala-Pivot");
        jugador43.setPosición("Pivot");
        jugador44.setPosición("Pivot");
        jugador45.setPosición("Base");
        jugador46.setPosición("Base");
        jugador47.setPosición("Escolta");
        jugador48.setPosición("Alero");
        jugador49.setPosición("Ala-Pivot");
        jugador50.setPosición("Pivot");
        jugador51.setPosición("Base");
        jugador52.setPosición("Escolta");
        jugador53.setPosición("Escolta");
        jugador54.setPosición("Alero");
        jugador55.setPosición("Ala-Pivot");
        jugador56.setPosición("Pivot");
        jugador57.setPosición("Base");
        jugador58.setPosición("Escolta");
        jugador59.setPosición("Alero");
        jugador60.setPosición("Ala-Pivot");
        jugador61.setPosición("Pivot");
        jugador62.setPosición("Base");
        jugador63.setPosición("Escolta");
        jugador64.setPosición("Escolta");
        jugador65.setPosición("Alero");
        jugador66.setPosición("Ala-Pivot");
        jugador67.setPosición("Pivot");
        jugador68.setPosición("Base");
        jugador69.setPosición("Base");
        jugador70.setPosición("Alero");
        jugador71.setPosición("Ala-Pivot");
        jugador72.setPosición("Pivot");
        jugador73.setPosición("Base");
        jugador74.setPosición("Escolta");
        jugador75.setPosición("Alero");
        jugador76.setPosición("Ala-Pivot");
        jugador77.setPosición("Pivot");
        jugador78.setPosición("Base");
        jugador79.setPosición("Escolta");
        jugador80.setPosición("Alero");
        jugador81.setPosición("Ala-Pivot");
        jugador82.setPosición("Pivot");
        jugador83.setPosición("Pivot");
        jugador84.setPosición("Base");
        jugador85.setPosición("Escolta");
        jugador86.setPosición("Alero");
        jugador87.setPosición("Ala-Pivot");
        jugador88.setPosición("Pivot");
        jugador89.setPosición("Base");
        jugador90.setPosición("Base");
        jugador91.setPosición("Escolta");
        jugador92.setPosición("Alero");
        jugador93.setPosición("Ala-Pivot");
        jugador94.setPosición("Ala-Pivot");
        jugador95.setPosición("Pivot");
        jugador96.setPosición("Pivot");
        jugador97.setPosición("Base");
        jugador98.setPosición("Escolta");
        jugador99.setPosición("Alero");
        juga0.setPosición("Ala-Pivot");
        juga1.setPosición("Pivot");
        juga2.setPosición("Base");
        juga3.setPosición("Escolta");
        juga4.setPosición("Alero");
        juga5.setPosición("Ala-Pivot");
        juga6.setPosición("Pivot");
        juga7.setPosición("Base");
        juga8.setPosición("Escolta");
        juga9.setPosición("Alero");
        juga10.setPosición("Ala-Pivot");
        juga11.setPosición("Pivot");
        juga12.setPosición("Base");
        juga13.setPosición("Base");
        juga14.setPosición("Escolta");
        juga15.setPosición("Alero");
        juga16.setPosición("Ala-Pivot");
        juga17.setPosición("Pivot");
        juga18.setPosición("Base");
        juga19.setPosición("Base");
        juga20.setPosición("Escolta");
        juga21.setPosición("Alero");
        juga22.setPosición("Ala-Pivot");
        juga23.setPosición("Pivot");
        juga24.setPosición("Base");
        juga25.setPosición("Escolta");
        juga26.setPosición("Alero");
        juga27.setPosición("Ala-Pivot");
        juga28.setPosición("Pivot");
        juga29.setPosición("Pivot");
        juga30.setPosición("Base");
        juga31.setPosición("Escolta");
        juga32.setPosición("Alero");
        juga33.setPosición("Ala-Pivot");
        juga34.setPosición("Pivot");
        juga35.setPosición("Base");
        juga36.setPosición("Base");
        juga37.setPosición("Escolta");
        juga38.setPosición("Alero");
        juga39.setPosición("Ala-Pivot");
        juga40.setPosición("Pivot");
        juga41.setPosición("Base");
        juga42.setPosición("Escolta");
        juga43.setPosición("Alero");
        juga44.setPosición("Ala-Pivot");
        juga45.setPosición("Pivot");
        juga46.setPosición("Base");
        juga47.setPosición("Escolta");
        juga48.setPosición("Alero");
        juga49.setPosición("Ala-Pivot");
        juga50.setPosición("Pivot");
        juga51.setPosición("Base");
        juga52.setPosición("Escolta");
        juga53.setPosición("Alero");
        juga54.setPosición("Ala-Pivot");
        juga55.setPosición("Pivot");
        juga56.setPosición("Pivot");
        juga57.setPosición("Base");
        juga58.setPosición("Escolta");
        juga59.setPosición("Escolta");
        juga60.setPosición("Alero");
        juga61.setPosición("Ala-Pivot");
        juga62.setPosición("Pivot");
        juga63.setPosición("Base");
        juga64.setPosición("Base");
        juga65.setPosición("Escolta");
        juga66.setPosición("Alero");
        juga67.setPosición("Ala-Pivot");
        juga68.setPosición("Pivot");
    }        
        //Asignar país a cada jugador
    public void PaisJugador() {
        jugador1.setPaís("Estados Unidos");
        jugador2.setPaís("Estados Unidos");
        jugador3.setPaís("Estados Unidos");
        jugador4.setPaís("Estados Unidos");
        jugador5.setPaís("Estados Unidos");
        jugador6.setPaís("Australia");
        jugador7.setPaís("Australia");
        jugador8.setPaís("Estados Unidos");
        jugador9.setPaís("Estados Unidos");
        jugador10.setPaís("Estados Unidos");
        jugador11.setPaís("Estados Unidos");
        jugador12.setPaís("Rep. Dominicana");
        jugador13.setPaís("Estados Unidos");
        jugador14.setPaís("Estados Unidos");
        jugador15.setPaís("Estados Unidos");
        jugador16.setPaís("Estados Unidos");
        jugador17.setPaís("Estados Unidos");
        jugador18.setPaís("Estados Unidos");
        jugador19.setPaís("Francia");
        jugador20.setPaís("Estados Unidos");
        jugador21.setPaís("Estados Unidos");
        jugador22.setPaís("Estados Unidos");
        jugador23.setPaís("España");
        jugador24.setPaís("Estados Unidos");
        jugador25.setPaís("Estados Unidos");
        jugador26.setPaís("Estados Unidos");
        jugador27.setPaís("Finlandia");
        jugador28.setPaís("Estados Unidos");
        jugador29.setPaís("Australia");
        jugador30.setPaís("Estados Unidos");
        jugador31.setPaís("Estados Unidos");
        jugador32.setPaís("Croacia");
        jugador33.setPaís("Estados Unidos");
        jugador34.setPaís("Eslovenia");
        jugador35.setPaís("Estados Unidos");
        jugador36.setPaís("Estados Unidos");
        jugador37.setPaís("Letonia");
        jugador38.setPaís("Túnez");
        jugador39.setPaís("Canadá");
        jugador40.setPaís("Estados Unidos");
        jugador41.setPaís("España");
        jugador42.setPaís("Estados Unidos");
        jugador43.setPaís("Serbia");
        jugador44.setPaís("Estados Unidos");
        jugador45.setPaís("Estados Unidos");
        jugador46.setPaís("España");
        jugador47.setPaís("Estados Unidos");
        jugador48.setPaís("Estados Unidos");
        jugador49.setPaís("Estados Unidos");
        jugador50.setPaís("Estados Unidos");
        jugador51.setPaís("Estados Unidos");
        jugador52.setPaís("Estados Unidos");
        jugador53.setPaís("Estados Unidos");
        jugador54.setPaís("Estados Unidos");
        jugador55.setPaís("Estados Unidos");
        jugador56.setPaís("Estados Unidos");
        jugador57.setPaís("Estados Unidos");
        jugador58.setPaís("Estados Unidos");
        jugador59.setPaís("Estados Unidos");
        jugador60.setPaís("Estados Unidos");
        jugador61.setPaís("Suiza");
        jugador62.setPaís("Estados Unidos");
        jugador63.setPaís("Estados Unidos");
        jugador64.setPaís("Estados Unidos");
        jugador65.setPaís("Croacia");
        jugador66.setPaís("Estados Unidos");
        jugador67.setPaís("Estados Unidos");
        jugador68.setPaís("Estados Unidos");
        jugador69.setPaís("Estados Unidos");
        jugador70.setPaís("Estados Unidos");
        jugador71.setPaís("Italia");
        jugador72.setPaís("Croacia");
        jugador73.setPaís("Estados Unidos");
        jugador74.setPaís("Estados Unidos");
        jugador75.setPaís("Estados Unidos");
        jugador76.setPaís("Estados Unidos");
        jugador77.setPaís("Estados Unidos");
        jugador78.setPaís("Estados Unidos");
        jugador79.setPaís("Estados Unidos");
        jugador80.setPaís("Estados Unidos");
        jugador81.setPaís("Brasil");
        jugador82.setPaís("Lituania");
        jugador83.setPaís("Estados Unidos");
        jugador84.setPaís("Eslovenia");
        jugador85.setPaís("Estados Unidos");
        jugador86.setPaís("Estados Unidos");
        jugador87.setPaís("Canadá");
        jugador88.setPaís("Estados Unidos");
        jugador89.setPaís("Estados Unidos");
        jugador90.setPaís("Estados Unidos");
        jugador91.setPaís("Estados Unidos");
        jugador92.setPaís("Estados Unidos");
        jugador93.setPaís("Grecia");
        jugador94.setPaís("Montenegro");
        jugador95.setPaís("Estados Unidos");
        jugador96.setPaís("España");
        jugador97.setPaís("Estados Unidos");
        jugador98.setPaís("Estados Unidos");
        jugador99.setPaís("Reino Unido");
        juga0.setPaís("Croacia");
        juga1.setPaís("Estados Unidos");
        juga2.setPaís("Estados Unidos");
        juga3.setPaís("Estados Unidos");
        juga4.setPaís("Estados Unidos");
        juga5.setPaís("Estados Unidos");
        juga6.setPaís("Estados Unidos");
        juga7.setPaís("Estados Unidos");
        juga8.setPaís("Estados Unidos");
        juga9.setPaís("Croacia");
        juga10.setPaís("Estados Unidos");
        juga11.setPaís("Estados Unidos");
        juga12.setPaís("Estados Unidos");
        juga13.setPaís("Alemania");
        juga14.setPaís("Estados Unidos");
        juga15.setPaís("Estados Unidos");
        juga16.setPaís("Estados Unidos");
        juga17.setPaís("Nueva Zelanda");
        juga18.setPaís("Estados Unidos");
        juga19.setPaís("Estados Unidos");
        juga20.setPaís("Estados Unidos");
        juga21.setPaís("Estados Unidos");
        juga22.setPaís("Estados Unidos");
        juga23.setPaís("Montenegro");
        juga24.setPaís("Australia");
        juga25.setPaís("Estados Unidos");
        juga26.setPaís("Estados Unidos");
        juga27.setPaís("Estados Unidos");
        juga28.setPaís("Camerún");
        juga29.setPaís("Serbia");
        juga30.setPaís("Estados Unidos");
        juga31.setPaís("Estados Unidos");
        juga32.setPaís("Estados Unidos");
        juga33.setPaís("Estados Unidos");
        juga34.setPaís("Croacia");
        juga35.setPaís("Estados Unidos");
        juga36.setPaís("Estados Unidos");
        juga37.setPaís("Estados Unidos");
        juga38.setPaís("Estados Unidos");
        juga39.setPaís("Estados Unidos");
        juga40.setPaís("Bosnia y Herzegovina");
        juga41.setPaís("Estados Unidos");
        juga42.setPaís("Estados Unidos");
        juga43.setPaís("Serbia");
        juga44.setPaís("Estados Unidos");
        juga45.setPaís("Estados Unidos");
        juga46.setPaís("Estados Unidos");
        juga47.setPaís("Italia");
        juga48.setPaís("Estados Unidos");
        juga49.setPaís("Estados Unidos");
        juga50.setPaís("Estados Unidos");
        juga51.setPaís("Estados Unidos");
        juga52.setPaís("Estados Unidos");
        juga53.setPaís("Estados Unidos");
        juga54.setPaís("Camerún");
        juga55.setPaís("España");
        juga56.setPaís("Rep. Congo");
        juga57.setPaís("España");
        juga58.setPaís("Estados Unidos");
        juga59.setPaís("Estados Unidos");
        juga60.setPaís("Suiza");
        juga61.setPaís("Estados Unidos");
        juga62.setPaís("Francia");
        juga63.setPaís("Rep. Checa");
        juga64.setPaís("Estados Unidos");
        juga65.setPaís("Estados Unidos");
        juga66.setPaís("Estados Unidos");
        juga67.setPaís("Estados Unidos");
        juga68.setPaís("Estados Unidos");
    }       
        //Asignar Altura a cada jugador
    public void AlturaJugador() {    
        jugador1.setAltura(BigDecimal.valueOf(1.88));
        jugador2.setAltura(BigDecimal.valueOf(1.96));
        jugador3.setAltura(BigDecimal.valueOf(1.98));
        jugador4.setAltura(BigDecimal.valueOf(2.08));
        jugador5.setAltura(BigDecimal.valueOf(2.11));
        jugador6.setAltura(BigDecimal.valueOf(2.13));
        jugador7.setAltura(BigDecimal.valueOf(1.91));
        jugador8.setAltura(BigDecimal.valueOf(1.93));
        jugador9.setAltura(BigDecimal.valueOf(2.01));
        jugador10.setAltura(BigDecimal.valueOf(2.03));
        jugador11.setAltura(BigDecimal.valueOf(2.03));
        jugador12.setAltura(BigDecimal.valueOf(2.08));
        jugador13.setAltura(BigDecimal.valueOf(1.96));
        jugador14.setAltura(BigDecimal.valueOf(1.98));
        jugador15.setAltura(BigDecimal.valueOf(2.01));
        jugador16.setAltura(BigDecimal.valueOf(2.03));
        jugador17.setAltura(BigDecimal.valueOf(2.11));
        jugador18.setAltura(BigDecimal.valueOf(1.85));
        jugador19.setAltura(BigDecimal.valueOf(2.03));
        jugador20.setAltura(BigDecimal.valueOf(2.01));
        jugador21.setAltura(BigDecimal.valueOf(2.06));
        jugador22.setAltura(BigDecimal.valueOf(2.13));
        jugador23.setAltura(BigDecimal.valueOf(2.10));
        jugador24.setAltura(BigDecimal.valueOf(1.93));
        jugador25.setAltura(BigDecimal.valueOf(1.96));
        jugador26.setAltura(BigDecimal.valueOf(2.03));
        jugador27.setAltura(BigDecimal.valueOf(2.13));
        jugador28.setAltura(BigDecimal.valueOf(2.13));
        jugador29.setAltura(BigDecimal.valueOf(1.93));
        jugador30.setAltura(BigDecimal.valueOf(1.91));
        jugador31.setAltura(BigDecimal.valueOf(2.08));
        jugador32.setAltura(BigDecimal.valueOf(2.12));
        jugador33.setAltura(BigDecimal.valueOf(1.98));
        jugador34.setAltura(BigDecimal.valueOf(2.01));
        jugador35.setAltura(BigDecimal.valueOf(1.98));
        jugador36.setAltura(BigDecimal.valueOf(2.03));
        jugador37.setAltura(BigDecimal.valueOf(2.21));
        jugador38.setAltura(BigDecimal.valueOf(2.17));
        jugador39.setAltura(BigDecimal.valueOf(1.93));
        jugador40.setAltura(BigDecimal.valueOf(1.98));
        jugador41.setAltura(BigDecimal.valueOf(2.06));
        jugador42.setAltura(BigDecimal.valueOf(2.03));
        jugador43.setAltura(BigDecimal.valueOf(2.08));
        jugador44.setAltura(BigDecimal.valueOf(2.11));
        jugador45.setAltura(BigDecimal.valueOf(1.91));
        jugador46.setAltura(BigDecimal.valueOf(1.91));
        jugador47.setAltura(BigDecimal.valueOf(1.88));
        jugador48.setAltura(BigDecimal.valueOf(1.93));
        jugador49.setAltura(BigDecimal.valueOf(2.08));
        jugador50.setAltura(BigDecimal.valueOf(2.11));
        jugador51.setAltura(BigDecimal.valueOf(1.91));
        jugador52.setAltura(BigDecimal.valueOf(2.01));
        jugador53.setAltura(BigDecimal.valueOf(1.98));
        jugador54.setAltura(BigDecimal.valueOf(2.06));
        jugador55.setAltura(BigDecimal.valueOf(2.01));
        jugador56.setAltura(BigDecimal.valueOf(2.11));
        jugador57.setAltura(BigDecimal.valueOf(1.83));
        jugador58.setAltura(BigDecimal.valueOf(1.93));
        jugador59.setAltura(BigDecimal.valueOf(1.96));
        jugador60.setAltura(BigDecimal.valueOf(1.98));
        jugador61.setAltura(BigDecimal.valueOf(2.08));
        jugador62.setAltura(BigDecimal.valueOf(1.83));
        jugador63.setAltura(BigDecimal.valueOf(1.98));
        jugador64.setAltura(BigDecimal.valueOf(1.93));
        jugador65.setAltura(BigDecimal.valueOf(2.03));
        jugador66.setAltura(BigDecimal.valueOf(2.03));
        jugador67.setAltura(BigDecimal.valueOf(2.11));
        jugador68.setAltura(BigDecimal.valueOf(1.85));
        jugador69.setAltura(BigDecimal.valueOf(1.85));
        jugador70.setAltura(BigDecimal.valueOf(1.98));
        jugador71.setAltura(BigDecimal.valueOf(2.08));
        jugador72.setAltura(BigDecimal.valueOf(2.16));
        jugador73.setAltura(BigDecimal.valueOf(1.85));
        jugador74.setAltura(BigDecimal.valueOf(2.06));
        jugador75.setAltura(BigDecimal.valueOf(2.03));
        jugador76.setAltura(BigDecimal.valueOf(2.06));
        jugador77.setAltura(BigDecimal.valueOf(2.13));
        jugador78.setAltura(BigDecimal.valueOf(1.85));
        jugador79.setAltura(BigDecimal.valueOf(1.98));
        jugador80.setAltura(BigDecimal.valueOf(1.98));
        jugador81.setAltura(BigDecimal.valueOf(2.06));
        jugador82.setAltura(BigDecimal.valueOf(2.13));
        jugador83.setAltura(BigDecimal.valueOf(2.11));
        jugador84.setAltura(BigDecimal.valueOf(1.91));
        jugador85.setAltura(BigDecimal.valueOf(1.93));
        jugador86.setAltura(BigDecimal.valueOf(2.01));
        jugador87.setAltura(BigDecimal.valueOf(2.13));
        jugador88.setAltura(BigDecimal.valueOf(2.08));
        jugador89.setAltura(BigDecimal.valueOf(1.85));
        jugador90.setAltura(BigDecimal.valueOf(1.91));
        jugador91.setAltura(BigDecimal.valueOf(1.96));
        jugador92.setAltura(BigDecimal.valueOf(2.03));
        jugador93.setAltura(BigDecimal.valueOf(2.11));
        jugador94.setAltura(BigDecimal.valueOf(2.08));
        jugador95.setAltura(BigDecimal.valueOf(2.13));
        jugador96.setAltura(BigDecimal.valueOf(2.13));
        jugador97.setAltura(BigDecimal.valueOf(1.88));
        jugador98.setAltura(BigDecimal.valueOf(1.91));
        jugador99.setAltura(BigDecimal.valueOf(2.06));
        juga0.setAltura(BigDecimal.valueOf(2.08));
        juga1.setAltura(BigDecimal.valueOf(2.11));
        juga2.setAltura(BigDecimal.valueOf(1.93));
        juga3.setAltura(BigDecimal.valueOf(1.93));
        juga4.setAltura(BigDecimal.valueOf(2.01));
        juga5.setAltura(BigDecimal.valueOf(2.06));
        juga6.setAltura(BigDecimal.valueOf(2.08));
        juga7.setAltura(BigDecimal.valueOf(1.91));
        juga8.setAltura(BigDecimal.valueOf(1.93));
        juga9.setAltura(BigDecimal.valueOf(2.03));
        juga10.setAltura(BigDecimal.valueOf(2.03));
        juga11.setAltura(BigDecimal.valueOf(2.11));
        juga12.setAltura(BigDecimal.valueOf(1.91));
        juga13.setAltura(BigDecimal.valueOf(1.85));
        juga14.setAltura(BigDecimal.valueOf(1.96));
        juga15.setAltura(BigDecimal.valueOf(2.06));
        juga16.setAltura(BigDecimal.valueOf(2.03));
        juga17.setAltura(BigDecimal.valueOf(2.13));
        juga18.setAltura(BigDecimal.valueOf(1.83));
        juga19.setAltura(BigDecimal.valueOf(1.98));
        juga20.setAltura(BigDecimal.valueOf(2.01));
        juga21.setAltura(BigDecimal.valueOf(2.08));
        juga22.setAltura(BigDecimal.valueOf(2.06));
        juga23.setAltura(BigDecimal.valueOf(2.13));
        juga24.setAltura(BigDecimal.valueOf(2.08));
        juga25.setAltura(BigDecimal.valueOf(1.93));
        juga26.setAltura(BigDecimal.valueOf(2.01));
        juga27.setAltura(BigDecimal.valueOf(2.06));
        juga28.setAltura(BigDecimal.valueOf(2.13));
        juga29.setAltura(BigDecimal.valueOf(2.22));
        juga30.setAltura(BigDecimal.valueOf(1.93));
        juga31.setAltura(BigDecimal.valueOf(1.98));
        juga32.setAltura(BigDecimal.valueOf(2.01));
        juga33.setAltura(BigDecimal.valueOf(2.03));
        juga34.setAltura(BigDecimal.valueOf(2.16));
        juga35.setAltura(BigDecimal.valueOf(1.91));
        juga36.setAltura(BigDecimal.valueOf(1.88));
        juga37.setAltura(BigDecimal.valueOf(1.91));
        juga38.setAltura(BigDecimal.valueOf(2.01));
        juga39.setAltura(BigDecimal.valueOf(2.06));
        juga40.setAltura(BigDecimal.valueOf(2.13));
        juga41.setAltura(BigDecimal.valueOf(1.83));
        juga42.setAltura(BigDecimal.valueOf(1.98));
        juga43.setAltura(BigDecimal.valueOf(1.98));
        juga44.setAltura(BigDecimal.valueOf(2.03));
        juga45.setAltura(BigDecimal.valueOf(2.13));
        juga46.setAltura(BigDecimal.valueOf(1.93));
        juga47.setAltura(BigDecimal.valueOf(1.96));
        juga48.setAltura(BigDecimal.valueOf(2.01));
        juga49.setAltura(BigDecimal.valueOf(2.03));
        juga50.setAltura(BigDecimal.valueOf(2.11));
        juga51.setAltura(BigDecimal.valueOf(1.85));
        juga52.setAltura(BigDecimal.valueOf(1.98));
        juga53.setAltura(BigDecimal.valueOf(2.01));
        juga54.setAltura(BigDecimal.valueOf(2.06));
        juga55.setAltura(BigDecimal.valueOf(2.16));
        juga56.setAltura(BigDecimal.valueOf(2.08));
        juga57.setAltura(BigDecimal.valueOf(1.93));
        juga58.setAltura(BigDecimal.valueOf(1.91));
        juga59.setAltura(BigDecimal.valueOf(2.01));
        juga60.setAltura(BigDecimal.valueOf(2.01));
        juga61.setAltura(BigDecimal.valueOf(2.08));
        juga62.setAltura(BigDecimal.valueOf(2.16));
        juga63.setAltura(BigDecimal.valueOf(2.01));
        juga64.setAltura(BigDecimal.valueOf(1.93));
        juga65.setAltura(BigDecimal.valueOf(1.96));
        juga66.setAltura(BigDecimal.valueOf(2.03));
        juga67.setAltura(BigDecimal.valueOf(2.03));
        juga68.setAltura(BigDecimal.valueOf(2.11));
    }    
        // Conectar con la base de datos
    public void Transacción() {
        Map<String, String> emfProperties = new HashMap<String, String>();
        emfProperties.put("javax.persistence.schema-generation.database.action", "create");
        EntityManagerFactory emf = Persistence.createEntityManagerFactory("NBAPU", emfProperties);
        EntityManager em = emf.createEntityManager();
        
    //Comenzar Transacción
            em.getTransaction().begin();
        //Nombre Equipo
            em.persist(equipoAtlanta);
            em.persist(equipoBoston);
            em.persist(equipoBrooklyn);
            em.persist(equipoCharlotte);
            em.persist(equipoChicago);
            em.persist(equipoCleveland);
            em.persist(equipoDallas);
            em.persist(equipoDenver);
            em.persist(equipoDetroit);
            em.persist(equipoGolden);
            em.persist(equipoHouston);
            em.persist(equipoIndiana);
            em.persist(equipoLAC);
            em.persist(equipoLAL);
            em.persist(equipoMemphis);
            em.persist(equipoMiami);
            em.persist(equipoBucks);
            em.persist(equipoMinnesota);
            em.persist(equipoNOP);
            em.persist(equipoNYK);
            em.persist(equipoOCT);
            em.persist(equipoMagic);
            em.persist(equipoPhila);
            em.persist(equipoSuns);
            em.persist(equipoPTB);
            em.persist(equipoKings);
            em.persist(equipoSpurs);
            em.persist(equipoRaptors);
            em.persist(equipoUtah);
            em.persist(equipoWizards);
       
            //Nombre Jugador
            em.persist(jugador1);
            em.persist(jugador2);
            em.persist(jugador3);
            em.persist(jugador4);
            em.persist(jugador5);
            em.persist(jugador6);
            em.persist(jugador7);
            em.persist(jugador8);
            em.persist(jugador9);
            em.persist(jugador10);
            em.persist(jugador11);
            em.persist(jugador12);
            em.persist(jugador13);
            em.persist(jugador14);
            em.persist(jugador15);
            em.persist(jugador16);
            em.persist(jugador17);
            em.persist(jugador18);
            em.persist(jugador19);
            em.persist(jugador20);
            em.persist(jugador21);
            em.persist(jugador22);
            em.persist(jugador23);
            em.persist(jugador24);
            em.persist(jugador25);
            em.persist(jugador26);
            em.persist(jugador27);
            em.persist(jugador28);
            em.persist(jugador29);
            em.persist(jugador30);
            em.persist(jugador31);
            em.persist(jugador32);
            em.persist(jugador33);
            em.persist(jugador34);
            em.persist(jugador35);
            em.persist(jugador36);
            em.persist(jugador37);
            em.persist(jugador38);
            em.persist(jugador39);
            em.persist(jugador40);
            em.persist(jugador41);
            em.persist(jugador42);
            em.persist(jugador43);
            em.persist(jugador44);
            em.persist(jugador45);
            em.persist(jugador46);
            em.persist(jugador47);
            em.persist(jugador48);
            em.persist(jugador49);
            em.persist(jugador50);
            em.persist(jugador51);
            em.persist(jugador52);
            em.persist(jugador53);
            em.persist(jugador54);
            em.persist(jugador55);
            em.persist(jugador56);
            em.persist(jugador57);
            em.persist(jugador58);
            em.persist(jugador59);
            em.persist(jugador60);
            em.persist(jugador61);
            em.persist(jugador62);
            em.persist(jugador63);
            em.persist(jugador64);
            em.persist(jugador65);
            em.persist(jugador66);
            em.persist(jugador67);
            em.persist(jugador68);
            em.persist(jugador69);
            em.persist(jugador70);
            em.persist(jugador71);
            em.persist(jugador72);
            em.persist(jugador73);
            em.persist(jugador74);
            em.persist(jugador75);
            em.persist(jugador76);
            em.persist(jugador77);
            em.persist(jugador78);
            em.persist(jugador79);
            em.persist(jugador80);
            em.persist(jugador81);
            em.persist(jugador82);
            em.persist(jugador83);
            em.persist(jugador84);
            em.persist(jugador85);
            em.persist(jugador86);
            em.persist(jugador87);
            em.persist(jugador88);
            em.persist(jugador89);
            em.persist(jugador90);
            em.persist(jugador91);
            em.persist(jugador92);
            em.persist(jugador93);
            em.persist(jugador94);
            em.persist(jugador95);
            em.persist(jugador96);
            em.persist(jugador97);
            em.persist(jugador98);
            em.persist(jugador99);
            em.persist(juga0);
            em.persist(juga1);
            em.persist(juga2);
            em.persist(juga3);
            em.persist(juga4);
            em.persist(juga5);
            em.persist(juga6);
            em.persist(juga7);
            em.persist(juga8);
            em.persist(juga9);
            em.persist(juga10);
            em.persist(juga11);
            em.persist(juga12);
            em.persist(juga13);
            em.persist(juga14);
            em.persist(juga15);
            em.persist(juga16);
            em.persist(juga17);
            em.persist(juga18);
            em.persist(juga19);
            em.persist(juga20);
            em.persist(juga21);
            em.persist(juga22);
            em.persist(juga23);
            em.persist(juga24);
            em.persist(juga25);
            em.persist(juga26);
            em.persist(juga27);
            em.persist(juga28);
            em.persist(juga29);
            em.persist(juga30);
            em.persist(juga31);
            em.persist(juga32);
            em.persist(juga33);
            em.persist(juga34);
            em.persist(juga35);
            em.persist(juga36);
            em.persist(juga37);
            em.persist(juga38);
            em.persist(juga39);
            em.persist(juga40);
            em.persist(juga41);
            em.persist(juga42);
            em.persist(juga43);
            em.persist(juga44);
            em.persist(juga45);
            em.persist(juga46);
            em.persist(juga47);
            em.persist(juga48);
            em.persist(juga49);
            em.persist(juga50);
            em.persist(juga51);
            em.persist(juga52);
            em.persist(juga53);
            em.persist(juga54);
            em.persist(juga55);
            em.persist(juga56);
            em.persist(juga57);
            em.persist(juga58);
            em.persist(juga59);
            em.persist(juga60);
            em.persist(juga61);
            em.persist(juga62);
            em.persist(juga63);
            em.persist(juga64);
            em.persist(juga65);
            em.persist(juga66);
            em.persist(juga67);
            em.persist(juga68);
        em.getTransaction().commit();
        
        // Cerrar la conexión con la base de datos
        em.close(); 
        emf.close(); 
        try { 
            DriverManager.getConnection("jdbc:derby:BDNBA;shutdown=true"); 
        } catch (SQLException ex) { 
        }
    }
}
